### ISSUE TITLE
ValueError: max() arg is an empty sequence in project_handler.py when processing EDF files

### ISSUE THREAD

**Issue by ZackGoldblum** [penn-cnt/SCALP_CONCAT-EEG#14]
**Description:**
Encountered a ValueError in project_handler.py during the execution of the neurovista function. The error occurs when attempting to retrieve the maximum sampling frequency from a metadata dictionary that appears to be empty. Note that the neurovista function is essentially identical to the scalp_00 function.

**Steps to Reproduce:**
1. Run the main processing script with the command python main.py with EDF files located at user_data/*.edf.
2. The initial data loading seems to work, as evidenced by the sampling frequency print statement from data_loader.py.
3. The process fails when reaching project_handler.py, specifically within the neurovista function.

**Expected Behavior:**
The script should correctly retrieve the sampling frequency from the metadata and proceed with the processing without throwing an exception.

**Actual Behavior:**
The script throws a ValueError: max() arg is an empty sequence indicating that the sampling frequency metadata is not being populated correctly.

**Error Log:**
Exception has occurred: ValueError
max() arg is an empty sequence
  File "/Users/zackg/Library/Mobile Documents/com~apple~CloudDocs/iCloud/littlab/pioneer_project/other_repos/SCALP_CONCAT-EEG/scripts/SCALP_CONCAT-EEG/modules/project_handler.py", line 85, in neurovista
    if self.dataframe.shape[0] <= int(max(self.metadata[self.file_cntr]['fs'])):
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zackg/Library/Mobile Documents/com~apple~CloudDocs/iCloud/littlab/pioneer_project/other_repos/SCALP_CONCAT-EEG/scripts/SCALP_CONCAT-EEG/main.py", line 110, in file_manager
    project_handlers.neurovista(self)
  File "/Users/zackg/Library/Mobile Documents/com~apple~CloudDocs/iCloud/littlab/pioneer_project/other_repos/SCALP_CONCAT-EEG/scripts/SCALP_CONCAT-EEG/main.py", line 65, in __init__
    self.file_manager(infiles, start_times, end_times)
  File "/Users/zackg/Library/Mobile Documents/com~apple~CloudDocs/iCloud/littlab/pioneer_project/other_repos/SCALP_CONCAT-EEG/scripts/SCALP_CONCAT-EEG/main.py", line 268, in start_analysis
    DM = data_manager(data_chunk,args,worker_id,barrier)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zackg/Library/Mobile Documents/com~apple~CloudDocs/iCloud/littlab/pioneer_project/other_repos/SCALP_CONCAT-EEG/scripts/SCALP_CONCAT-EEG/main.py", line 476, in <module>
    start_analysis(input_parameters, args, 0, None)
ValueError: max() arg is an empty sequence

**Code Snippets:** 
\# data_loader.py snippet
sample_frequency = np.array([ichannel['sample_frequency'] for ichannel in self.channel_metadata])
print(f"SAMPLING FREQ (data_loader): {sample_frequency}")
metadata_handler.set_sampling_frequency(self, sample_frequency)

\# project_handler.py snippet
print(f"SAMPLING FREQ (project handler): {self.metadata[self.file_cntr]['fs']}")
if self.dataframe.shape[0] <= int(max(self.metadata[self.file_cntr]['fs'])):
    pass
else:
    ...
    
**Possible Cause:**
It seems there might be a disconnect between the data_loader and the project_handler, where the sampling frequencies are not being correctly transferred or stored in the metadata.

**Suggested Fix:**
Please check why the metadata[self.file_cntr]['fs'] is empty in project_handler.py. It may involve ensuring the metadata is correctly updated after loading the data or verifying that the file counter (self.file_cntr) is referencing the correct metadata index.

**Comment by ZackGoldblum** [comment]
@UPennBJPrager I created an Issue here to help track it.

**Comment by UPennBJPrager** [comment]
Can you check for me whether you return a valid self.channel_map_out array? The most likely cause is when modules.channel_mapping:pipeline updates the sampling frequencies using the mapped channel names. You should be able to use the direct_inputs function to see what values you return. @ZackGoldblum

**Comment by ZackGoldblum** [comment]
Seems like this is getting toward the root of the issue since args.channel_list and channel_mapping default to HUP1020. I'll need to add more code specific to NEUROVISTA, I expect this will fix the issue. Will update when I'm done.

**Comment by UPennBJPrager** [comment]
If you add the channel mapping to main.py:main allowed_channel_args list, and add it to the logic gate in channel_maping.py:mapping_logic it should enable your code. @ZackGoldblum

**Comment by ZackGoldblum** [comment]
Thanks @UPennBJPrager I'll do that!

**Comment by ZackGoldblum** [comment]
@UPennBJPrager This resolved the issue, thank you for the help!
